name: Docker CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up JDK
        run: |
          sudo apt-get install -y openjdk-11-jdk
        

      - name: Build Docker Image
        run: docker build -t wardasajjad/maven-java-monitoring-example-cicd:latest .

      - name: Push Docker Image to Docker Hub
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker push wardasajjad/maven-java-monitoring-example-cicd:latest
